version: "3.1"

services:
  adventure_works:
    build: .
    user: '0:0'
    container_name: adventure_works
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
      MSSQL_PID: Express
    volumes:
      - sqlserver-data:/docker-entrypoint-initdb.d
volumes:
  sqlserver-data: